# Aktuellen Stand der Wissenschaft und Technik

Linearmotoren sind am besten bekannt aus ihrer Anwendung in linearen Transportsystemen (wie dem "Maglev"), die bereits seit einigen Jahrzehnten in Betrieb sind und in mehreren Städten auf der ganzen Welt ihren Dienst tun [@hellinger2009; @palka2021]. Die Linearmotoren, die diese Transportsysteme antreiben, wurden bereits im 19. und frühen 20. Jahrhundert patentiert und Anwendungen entstanden in den späten 1940er Jahren durch den Visionär Eric Laithwaite vom Imperial College in London [@hellinger2009]. Die Anwendung von Linearmotoren für Transportsysteme in der zweiten Hälfte des 20. Jahrhunderts stimulierte eine rasante Entwicklung von Linearmotoren. Dies enthüllte auch die Konstruktionsvorteile des Linearmotors gegenüber herkömmlichen Rotationsmotoren, wie zum Beispiel steuerbare Normalkräfte, direkter Schub ohne Haftung zwischen Rädern und Schienen, wobei letzterer zu geringerem Verschleiß der Kontaktpunkte und damit zu weniger Wartungsaufwand führt. Aufgrund der fortschreitenden Automatisierung vieler Prozesse werden Linearmotoren heutzutage zunehmend in vielen hochpräzisen Industriezweigen eingesetzt, darunter: Öl und Gas, medizinischen Laboren, chirurgische Geräte und Implantate sowie die Herstellung von Halbleiterchips, wodurch sie langsam die traditionellen mechanischen, hydraulischen oder pneumatischen Linearmotoren ersetzen [@gieras2018].

<!-- Linear motors are probably best known from their application in linear motion transit systems (such as the "Maglev"), which have already been in operation for a few decades, and they are serving in several cities around the world [@hellinger2009; @palka2021]. The linear motors that drive these transit systems where already patented in the 19th century and early 20th century and applications arose in the late 1940s by the visionary Eric Laithwaite of Imperial College in London [@hellinger2009]. The application of linear motors for transportation systems in the second half of the 20th century stimulated rapid developments in linear motors. This also unveiled the design benefits of the linear motor over conventional rotary motors, such as controllable normal forces, direct thrust with no adhesion between wheels and tracks, where the latter results in less wear of contact points and thus reducing maintenance. Due to progressive automation of many processes, linear motors are nowadays increasingly used in many high precision branches of industry, including: oil and gas, medical surgical devices and implants, and semiconductor chip manufacturing, thereby slowly replacing the traditional mechanical, hydraulic or pneumatic linear motion systems [@gieras2018].  -->

Rotations- und Linearmotoren sind ähnlich aufgebaut, aber anstelle eines Rotors, der sich in einem zylindrischen Mantel aus Blech (Stator) dreht, bewegt sich der Rotor (oder Läufer) in einer geraden Linie auf einem geraden Stator (oder einer Reaktionsschiene), die mechanische Bewegung ist synchron und 1:1 proportional mit dem magnetischen Wanderfeld [@gieras2018]. Zwei am weitesten verbreitete Untertypen von Linearmotoren sind Eisenkern-Linearmotoren und eisenlose Linearmotoren. während beide Typen üblicherweise mit einer Reihe von Permanentmagneten (auf der Reaktionsschiene) verbunden sind, bezieht sich der Unterschied auf den Läufer, der das wandernde Magnetfeld bereitstellt [@chou2016; @gieras2018]. Die Spule ist entweder um einem Eisenkern gewickelt oder die Kern der Spuleneinheit umfasst kein Eisen. Bei letzterer Konstruktion sind die Spulen des Treibers in ein Epoxidharz eingebettet [@collins2016; @gieras2018]. Die eisenlosen Linearmotoren haben daher eine geringere Masse und keine inhärente magnetischen Anziehungskräfte, und können daher dynamischere Bewegungen ausführen mit einem konstanter Geschwindigkeit [0,01% Geschwindigkeitsvariation @collins2016]. Ein weiterer Unterschied des Läufer besteht darin, dass er entweder I- oder Y-förmig ist, wobei der Läufers zwischen zwei Magnetstreifen gleitet, die von der Seite einer U-förmigen Reaktionsschiene angebracht sind. Ohne die inhärente Anziehungskraft, wie es bei Linearmotoren mit Eisenkern der Fall ist, lassen sich diese eisenlosen Geräte einfacher zusammenbauen und verursachen auch weniger "Cogging" (d. h. Schwankungen in der Schubkraft), wodurch die Präzision noch weiter erhöht und die Wartung noch weiter minimiert wird [@collins2016] .

<!-- Rotational and linear motors are similar in design, but instead of a rotor spinning inside a spherical stator, the rotor (or forcer) moves in a straight line on a straight stator (or reaction rail), mechanical movement is synchronous and 1:1 proportional with the travelling magnetic field [@gieras2018]. Two subtypes of linear motors most widely encountered are ironcore and ironless linear motors. Whereas both types commonly connect to a series of permanent magnets (on the reaction rail), the difference relates to the forcer which provides the travelling magnetic field [@chou2016; @gieras2018]. It is either a coil wrapped around a ferromagnetic material (iron) or without a ferromagnetic core. In the latter construction the coils of the forcer are embedded within an epoxy resin [@collins2016; @gieras2018]. The ironless linear motors have therefore a lower mass and can perform more dynamic movements of steady speed (0.01% speed variation) with velocities ranging up to 8$\,\text{ms}^{-1}$ [@collins2016]. Another difference of the forcer is that it is either I- or Y-shaped, with the forcer gliding between two magnetic strips mounted from the side of an U-shaped reaction rail. Without the inherent attractive force, as is the case for iron core linear motors, these ironless devices are easier to ensemble and causes also less cogging (i.e., variation in the thrust force), thus increasing precision and minimising maintenance even further [@collins2016]. -->
